[package]
name = "reconl-backend-softcpu"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
reconl-core = { workspace = true }
reconl-raster = { workspace = true }
reconl-shadow = { workspace = true }
reconl-resource = { workspace = true }

[lib]
name = "reconl_backend_softcpu"
path = "src/lib.rs"
