//! The ABI layout pin: the shipped header, compiled by a real C compiler,
//! against the `#[repr(C)]` mirror in `ffi/src/abi.rs`.
//!
//! `tests/abi.rs` drives the exports; this test checks what their arguments are
//! made of. It writes a C file of `_Static_assert`s - one for every struct's
//! `sizeof`, one per field for its `offsetof` and its own `sizeof`, and a
//! `_Generic` check that the field's category (integer, float, pointer) is the
//! one the Rust side declares - and asks a C compiler to compile it against
//! `include/reconl/reconl.h`. A field added, removed, reordered or retyped on
//! one side and not the other stops this test, which is the only way an ABI
//! stays a contract. The same file asserts every macro, constant and enum member
//! the header exports against the Rust value the implementation uses, so a
//! renumbered code, flag or enumerator fails the same way a retyped field does.
//!
//! It skips, with a printed reason, when the host has no C compiler, the way the
//! d3d11 legs skip without a usable device. On failure the generated file is
//! left in `CARGO_TARGET_TMPDIR` and its path printed, so a red run is
//! diagnosable from the compiler's own messages.

use core::ffi::c_void;
use std::fmt::Write as _;
use std::mem::offset_of;
use std::path::{Path, PathBuf};
use std::process::Command;

use reconl::abi::*;
use reconl_core::error::Code;
use reconl_core::log::Level;
use reconl_core::tier::{self as core_tier, ShadowEvent, ShadowFilter, Tier, TierReason};
use reconl_core::StructHeader;
use reconl_raster::shade;
use reconl_raster::texture;
use reconl_raster::{COMPARE_GREATER, COMPARE_LESS, CULL_BACK, CULL_FRONT, CULL_NONE};

// `f!` is one table row: the C field name, the Rust offset, the Rust field
// size, and the field's category. `as "name"` is for the two fields whose C
// names are not their Rust names (`ReconLBase::type` and `ReconLLight::type`).
macro_rules! f {
    ($t:ty, $f:ident, $ty:ty, $kind:literal) => {
        (stringify!($f), offset_of!($t, $f), size_of::<$ty>(), $kind)
    };
    ($t:ty, $f:ident as $name:literal, $ty:ty, $kind:literal) => {
        ($name, offset_of!($t, $f), size_of::<$ty>(), $kind)
    };
}

#[test]
fn the_header_and_the_rust_mirror_agree_on_every_struct_layout() {
    let path = write_generated(&generated());
    match compile(&path) {
        Compile::Passed => {}
        Compile::NoCompiler => eprintln!(
            "no C compiler on this host (tried CC, cc, gcc, clang); \
             skipping the header/Rust layout check"
        ),
        Compile::Failed(report) => panic!(
            "the shipped header and the Rust mirror in ffi/src/abi.rs disagree about \
             the ABI layout. The generated C (left at {}) did not compile:\n\n{report}",
            path.display()
        ),
    }
}

enum Compile {
    Passed,
    NoCompiler,
    Failed(String),
}

/// Compile the generated file with the first compiler that runs it. A compiler
/// that is present but rejects the file is a failure, not a skip: a broken
/// toolchain must not silently retire the check.
fn compile(c_file: &Path) -> Compile {
    let include = Path::new(env!("CARGO_MANIFEST_DIR")).join("../include");
    let mut candidates = Vec::new();
    if let Ok(cc) = std::env::var("CC") {
        if !cc.trim().is_empty() {
            candidates.push(cc);
        }
    }
    candidates.extend(["cc", "gcc", "clang", "x86_64-w64-mingw32-gcc"].map(str::to_string));

    let mut report = String::new();
    let mut ran = false;
    for cc in candidates {
        let Ok(out) = Command::new(&cc)
            .args(["-std=c11", "-fsyntax-only", "-I"])
            .arg(&include)
            .arg(c_file)
            .output()
        else {
            continue;
        };
        ran = true;
        if out.status.success() {
            return Compile::Passed;
        }
        let _ = write!(report, "--- {cc} ---\n{}", String::from_utf8_lossy(&out.stderr));
    }
    if ran {
        Compile::Failed(report)
    } else {
        Compile::NoCompiler
    }
}

/// The file is per-process because the suite runs fully parallel.
fn write_generated(source: &str) -> PathBuf {
    let dir = PathBuf::from(env!("CARGO_TARGET_TMPDIR"));
    std::fs::create_dir_all(&dir).expect("create CARGO_TARGET_TMPDIR");
    let path = dir.join(format!("abi_layout.generated.{}.c", std::process::id()));
    std::fs::write(&path, source).expect("write the generated C file");
    path
}

fn generated() -> String {
    let mut c = String::from(
        "/* Generated by ffi/tests/abi_layout.rs from the Rust mirror in\n\
         * ffi/src/abi.rs; compiled, never run, against include/reconl/reconl.h.\n\
         * Do not edit: change the struct or the mirror and run the test. */\n\
         #include <stddef.h>\n\
         #include <reconl/reconl.h>\n",
    );

    // The base every other struct starts with. `ReconLBase::type` is
    // `StructHeader::struct_type` in Rust - the C name is the header's.
    struct_layout(&mut c, "ReconLBase", size_of::<StructHeader>(), &[
        f!(StructHeader, struct_size, u32, "int"),
        f!(StructHeader, struct_type as "type", u32, "int"),
        f!(StructHeader, next, *const c_void, "ptr"),
    ]);

    struct_layout(&mut c, "ReconLAllocator", size_of::<ReconLAllocator>(), &[
        f!(ReconLAllocator, alloc, Option<unsafe extern "C" fn(*mut c_void, usize, usize) -> *mut c_void>, "ptr"),
        f!(ReconLAllocator, realloc, Option<unsafe extern "C" fn(*mut c_void, *mut c_void, usize, usize, usize) -> *mut c_void>, "ptr"),
        f!(ReconLAllocator, free, Option<unsafe extern "C" fn(*mut c_void, *mut c_void, usize)>, "ptr"),
        f!(ReconLAllocator, user, *mut c_void, "ptr"),
    ]);

    struct_layout(&mut c, "ReconLBackendProbe", size_of::<ReconLBackendProbe>(), &[
        f!(ReconLBackendProbe, backend, u32, "int"),
        f!(ReconLBackendProbe, name, [u8; RECONL_MAX_NAME], "ints"),
        f!(ReconLBackendProbe, usable, i32, "int"),
        f!(ReconLBackendProbe, caps, u32, "int"),
        f!(ReconLBackendProbe, best_tier, u32, "int"),
        f!(ReconLBackendProbe, vram_bytes, u64, "int"),
        f!(ReconLBackendProbe, ram_bytes, u64, "int"),
        f!(ReconLBackendProbe, max_cascades, u32, "int"),
        f!(ReconLBackendProbe, shadow_texel_budget, u64, "int"),
        f!(ReconLBackendProbe, device_name, [u8; RECONL_MAX_NAME], "ints"),
        f!(ReconLBackendProbe, note, [u8; RECONL_MAX_MESSAGE], "ints"),
    ]);

    struct_layout(&mut c, "ReconLProbeDesc", size_of::<ReconLProbeDesc>(), &[
        f!(ReconLProbeDesc, base, StructHeader, "none"),
        f!(ReconLProbeDesc, flags, u32, "int"),
        f!(ReconLProbeDesc, spill_dir, *const i8, "ptr"),
    ]);

    struct_layout(&mut c, "ReconLProbeInfo", size_of::<ReconLProbeInfo>(), &[
        f!(ReconLProbeInfo, base, StructHeader, "none"),
        f!(ReconLProbeInfo, entry_count, u32, "int"),
        f!(ReconLProbeInfo, entries, [ReconLBackendProbe; RECONL_MAX_BACKENDS], "none"),
        f!(ReconLProbeInfo, recommended_tier, u32, "int"),
        f!(ReconLProbeInfo, recommended_backend, u32, "int"),
    ]);

    struct_layout(&mut c, "ReconLDeviceLimits", size_of::<ReconLDeviceLimits>(), &[
        f!(ReconLDeviceLimits, base, StructHeader, "none"),
        f!(ReconLDeviceLimits, vram_bytes, u64, "int"),
        f!(ReconLDeviceLimits, ram_bytes, u64, "int"),
        f!(ReconLDeviceLimits, disk_bytes, u64, "int"),
        f!(ReconLDeviceLimits, max_allocation_bytes, u64, "int"),
        f!(ReconLDeviceLimits, shadow_texel_budget_bytes, u64, "int"),
        f!(ReconLDeviceLimits, worker_threads_max, u32, "int"),
        f!(ReconLDeviceLimits, tile_size_min, u32, "int"),
        f!(ReconLDeviceLimits, max_cascades, u32, "int"),
        f!(ReconLDeviceLimits, max_lights, u32, "int"),
        f!(ReconLDeviceLimits, caps, u32, "int"),
        f!(ReconLDeviceLimits, backend, u32, "int"),
        f!(ReconLDeviceLimits, device_name, [u8; RECONL_MAX_NAME], "ints"),
        f!(ReconLDeviceLimits, driver, [u8; RECONL_MAX_NAME], "ints"),
    ]);

    struct_layout(&mut c, "ReconLMemoryBudget", size_of::<ReconLMemoryBudget>(), &[
        f!(ReconLMemoryBudget, base, StructHeader, "none"),
        f!(ReconLMemoryBudget, vram_cap_bytes, u64, "int"),
        f!(ReconLMemoryBudget, ram_cap_bytes, u64, "int"),
        f!(ReconLMemoryBudget, disk_cap_bytes, u64, "int"),
        f!(ReconLMemoryBudget, allow_disk_spill, u32, "int"),
        f!(ReconLMemoryBudget, reserved, u32, "int"),
        f!(ReconLMemoryBudget, spill_dir, *const i8, "ptr"),
    ]);

    struct_layout(&mut c, "ReconLDeviceDesc", size_of::<ReconLDeviceDesc>(), &[
        f!(ReconLDeviceDesc, base, StructHeader, "none"),
        f!(ReconLDeviceDesc, backend_hint, u32, "int"),
        f!(ReconLDeviceDesc, tier_hint, u32, "int"),
        f!(ReconLDeviceDesc, allow_downgrade, u32, "int"),
        f!(ReconLDeviceDesc, worker_threads, u32, "int"),
        f!(ReconLDeviceDesc, target_frame_ms, u32, "int"),
        f!(ReconLDeviceDesc, downgrade_after_frames, u32, "int"),
        f!(ReconLDeviceDesc, seed, u32, "int"),
        f!(ReconLDeviceDesc, flags, u32, "int"),
        f!(ReconLDeviceDesc, budget, *const ReconLMemoryBudget, "ptr"),
        f!(ReconLDeviceDesc, allocator, ReconLAllocator, "none"),
        f!(ReconLDeviceDesc, backend_desc, *const c_void, "ptr"),
    ]);

    struct_layout(&mut c, "ReconLSwapchainDesc", size_of::<ReconLSwapchainDesc>(), &[
        f!(ReconLSwapchainDesc, base, StructHeader, "none"),
        f!(ReconLSwapchainDesc, width, u32, "int"),
        f!(ReconLSwapchainDesc, height, u32, "int"),
        f!(ReconLSwapchainDesc, format, u32, "int"),
        f!(ReconLSwapchainDesc, image_count, u32, "int"),
        f!(ReconLSwapchainDesc, present_to_memory, u32, "int"),
        f!(ReconLSwapchainDesc, depth_format, u32, "int"),
        f!(ReconLSwapchainDesc, flags, u32, "int"),
        f!(ReconLSwapchainDesc, reserved, u32, "int"),
    ]);

    struct_layout(&mut c, "ReconLBufferDesc", size_of::<ReconLBufferDesc>(), &[
        f!(ReconLBufferDesc, base, StructHeader, "none"),
        f!(ReconLBufferDesc, size_bytes, u64, "int"),
        f!(ReconLBufferDesc, usage, u32, "int"),
        f!(ReconLBufferDesc, reserved, u32, "int"),
        f!(ReconLBufferDesc, data, *const c_void, "ptr"),
        f!(ReconLBufferDesc, data_size, u64, "int"),
        f!(ReconLBufferDesc, debug_name, *const i8, "ptr"),
    ]);

    struct_layout(&mut c, "ReconLTextureDesc", size_of::<ReconLTextureDesc>(), &[
        f!(ReconLTextureDesc, base, StructHeader, "none"),
        f!(ReconLTextureDesc, width, u32, "int"),
        f!(ReconLTextureDesc, height, u32, "int"),
        f!(ReconLTextureDesc, mip_levels, u32, "int"),
        f!(ReconLTextureDesc, array_layers, u32, "int"),
        f!(ReconLTextureDesc, format, u32, "int"),
        f!(ReconLTextureDesc, usage, u32, "int"),
        f!(ReconLTextureDesc, reserved, u32, "int"),
        f!(ReconLTextureDesc, debug_name, *const i8, "ptr"),
    ]);

    struct_layout(&mut c, "ReconLTextureLevel", size_of::<ReconLTextureLevel>(), &[
        f!(ReconLTextureLevel, base, StructHeader, "none"),
        f!(ReconLTextureLevel, mip, u32, "int"),
        f!(ReconLTextureLevel, layer, u32, "int"),
        f!(ReconLTextureLevel, row_pitch, u32, "int"),
        f!(ReconLTextureLevel, row_count, u32, "int"),
        f!(ReconLTextureLevel, data, *const c_void, "ptr"),
        f!(ReconLTextureLevel, data_size, u64, "int"),
    ]);

    struct_layout(&mut c, "ReconLSamplerDesc", size_of::<ReconLSamplerDesc>(), &[
        f!(ReconLSamplerDesc, base, StructHeader, "none"),
        f!(ReconLSamplerDesc, filter, u32, "int"),
        f!(ReconLSamplerDesc, wrap_u, u32, "int"),
        f!(ReconLSamplerDesc, wrap_v, u32, "int"),
        f!(ReconLSamplerDesc, wrap_w, u32, "int"),
        f!(ReconLSamplerDesc, max_anisotropy, u32, "int"),
        f!(ReconLSamplerDesc, mip_lod_bias, f32, "float"),
        f!(ReconLSamplerDesc, reserved, u32, "int"),
    ]);

    struct_layout(&mut c, "ReconLVertex", size_of::<ReconLVertex>(), &[
        f!(ReconLVertex, position, [f32; 3], "floats"),
        f!(ReconLVertex, normal, [f32; 3], "floats"),
        f!(ReconLVertex, uv, [f32; 2], "floats"),
        f!(ReconLVertex, color, [f32; 4], "floats"),
    ]);

    struct_layout(&mut c, "ReconLPipelineDesc", size_of::<ReconLPipelineDesc>(), &[
        f!(ReconLPipelineDesc, base, StructHeader, "none"),
        f!(ReconLPipelineDesc, shading, u32, "int"),
        f!(ReconLPipelineDesc, blend, u32, "int"),
        f!(ReconLPipelineDesc, cull, u32, "int"),
        f!(ReconLPipelineDesc, depth_compare, u32, "int"),
        f!(ReconLPipelineDesc, depth_write, u32, "int"),
        f!(ReconLPipelineDesc, texture_slots, u32, "int"),
        f!(ReconLPipelineDesc, texture_formats, [u32; RECONL_MAX_TEXTURE_SLOTS], "ints"),
        f!(ReconLPipelineDesc, receives_shadow, u32, "int"),
        f!(ReconLPipelineDesc, casts_shadow, u32, "int"),
        f!(ReconLPipelineDesc, flags, u32, "int"),
        f!(ReconLPipelineDesc, reserved, u32, "int"),
        f!(ReconLPipelineDesc, debug_name, *const i8, "ptr"),
    ]);

    struct_layout(&mut c, "ReconLLight", size_of::<ReconLLight>(), &[
        f!(ReconLLight, base, StructHeader, "none"),
        f!(ReconLLight, r#type as "type", u32, "int"),
        f!(ReconLLight, cast_shadow, u32, "int"),
        f!(ReconLLight, shadow_priority, u32, "int"),
        f!(ReconLLight, shadow_quality, u32, "int"),
        f!(ReconLLight, position, [f32; 3], "floats"),
        f!(ReconLLight, direction, [f32; 3], "floats"),
        f!(ReconLLight, color, [f32; 3], "floats"),
        f!(ReconLLight, intensity, f32, "float"),
        f!(ReconLLight, range, f32, "float"),
        f!(ReconLLight, cone_inner_deg, f32, "float"),
        f!(ReconLLight, cone_outer_deg, f32, "float"),
        f!(ReconLLight, reserved, u32, "int"),
    ]);

    struct_layout(&mut c, "ReconLLightList", size_of::<ReconLLightList>(), &[
        f!(ReconLLightList, base, StructHeader, "none"),
        f!(ReconLLightList, count, u32, "int"),
        f!(ReconLLightList, reserved, u32, "int"),
        f!(ReconLLightList, lights, *const ReconLLight, "ptr"),
    ]);

    struct_layout(&mut c, "ReconLShadowConfig", size_of::<ReconLShadowConfig>(), &[
        f!(ReconLShadowConfig, base, StructHeader, "none"),
        f!(ReconLShadowConfig, enabled, u32, "int"),
        f!(ReconLShadowConfig, cascade_count, u32, "int"),
        f!(ReconLShadowConfig, texel_budget_bytes, u64, "int"),
        f!(ReconLShadowConfig, filter, u32, "int"),
        f!(ReconLShadowConfig, max_distance, f32, "float"),
        f!(ReconLShadowConfig, blend_band, f32, "float"),
        f!(ReconLShadowConfig, normal_bias, f32, "float"),
        f!(ReconLShadowConfig, depth_bias, f32, "float"),
        f!(ReconLShadowConfig, slope_bias, f32, "float"),
        f!(ReconLShadowConfig, resolution_scale, f32, "float"),
        f!(ReconLShadowConfig, allow_disk_cache, u32, "int"),
        f!(ReconLShadowConfig, freeze_static_cascade, u32, "int"),
        f!(ReconLShadowConfig, refresh_interval_frames, u32, "int"),
        f!(ReconLShadowConfig, reserved, u32, "int"),
    ]);

    struct_layout(&mut c, "ReconLShadowStats", size_of::<ReconLShadowStats>(), &[
        f!(ReconLShadowStats, base, StructHeader, "none"),
        f!(ReconLShadowStats, cascades_active, u32, "int"),
        f!(ReconLShadowStats, map_width, u32, "int"),
        f!(ReconLShadowStats, map_height, u32, "int"),
        f!(ReconLShadowStats, map_bytes, u32, "int"),
        f!(ReconLShadowStats, filter_active, u32, "int"),
        f!(ReconLShadowStats, filter_requested, u32, "int"),
        f!(ReconLShadowStats, shadow_pass_ns, u64, "int"),
        f!(ReconLShadowStats, cascade_fit_ns, u64, "int"),
        f!(ReconLShadowStats, cache_bytes_read, u64, "int"),
        f!(ReconLShadowStats, cache_bytes_hit, u64, "int"),
        f!(ReconLShadowStats, cache_hits, u32, "int"),
        f!(ReconLShadowStats, cache_misses, u32, "int"),
        f!(ReconLShadowStats, cache_corrupt, u32, "int"),
        f!(ReconLShadowStats, fail_safe_unshadowed, u32, "int"),
        f!(ReconLShadowStats, frozen_cascades, u32, "int"),
        f!(ReconLShadowStats, shadowed_lights, u32, "int"),
        f!(ReconLShadowStats, point_lights_capped, u32, "int"),
    ]);

    struct_layout(&mut c, "ReconLMemoryStats", size_of::<ReconLMemoryStats>(), &[
        f!(ReconLMemoryStats, base, StructHeader, "none"),
        f!(ReconLMemoryStats, ram_resident_bytes, u64, "int"),
        f!(ReconLMemoryStats, ram_budget_bytes, u64, "int"),
        f!(ReconLMemoryStats, ram_peak_bytes, u64, "int"),
        f!(ReconLMemoryStats, spill_resident_bytes, u64, "int"),
        f!(ReconLMemoryStats, spill_disk_bytes, u64, "int"),
        f!(ReconLMemoryStats, spill_disk_cap_bytes, u64, "int"),
        f!(ReconLMemoryStats, spill_evicted_bytes, u64, "int"),
        f!(ReconLMemoryStats, spill_cache_bytes, u64, "int"),
        f!(ReconLMemoryStats, spill_entries, u32, "int"),
        f!(ReconLMemoryStats, spill_evictions, u32, "int"),
        f!(ReconLMemoryStats, spill_compactions, u32, "int"),
        f!(ReconLMemoryStats, spill_recovered_entries, u32, "int"),
        f!(ReconLMemoryStats, spill_errors, u32, "int"),
        f!(ReconLMemoryStats, host_alloc_calls, u32, "int"),
        f!(ReconLMemoryStats, host_alloc_bytes, u64, "int"),
        f!(ReconLMemoryStats, host_free_calls, u32, "int"),
        f!(ReconLMemoryStats, reserved, u32, "int"),
    ]);

    struct_layout(&mut c, "ReconLFrameTiming", size_of::<ReconLFrameTiming>(), &[
        f!(ReconLFrameTiming, base, StructHeader, "none"),
        f!(ReconLFrameTiming, frame_index, u64, "int"),
        f!(ReconLFrameTiming, total_ns, u64, "int"),
        f!(ReconLFrameTiming, shadow_ns, u64, "int"),
        f!(ReconLFrameTiming, raster_ns, u64, "int"),
        f!(ReconLFrameTiming, bin_ns, u64, "int"),
        f!(ReconLFrameTiming, upload_ns, u64, "int"),
        f!(ReconLFrameTiming, spill_wait_ns, u64, "int"),
        f!(ReconLFrameTiming, min_ns, u64, "int"),
        f!(ReconLFrameTiming, avg_ns, u64, "int"),
        f!(ReconLFrameTiming, max_ns, u64, "int"),
        f!(ReconLFrameTiming, tiles_total, u32, "int"),
        f!(ReconLFrameTiming, tiles_rendered, u32, "int"),
        f!(ReconLFrameTiming, triangles_in, u32, "int"),
        f!(ReconLFrameTiming, triangles_binned, u32, "int"),
        f!(ReconLFrameTiming, triangles_culled, u32, "int"),
        f!(ReconLFrameTiming, pixels_shaded, u32, "int"),
        f!(ReconLFrameTiming, worker_threads, u32, "int"),
        f!(ReconLFrameTiming, resolution_scale, f32, "float"),
        f!(ReconLFrameTiming, reserved, u32, "int"),
    ]);

    struct_layout(&mut c, "ReconLDowngrade", size_of::<ReconLDowngrade>(), &[
        f!(ReconLDowngrade, from, u32, "int"),
        f!(ReconLDowngrade, to, u32, "int"),
        f!(ReconLDowngrade, reason, u32, "int"),
        f!(ReconLDowngrade, frame_index, u64, "int"),
        f!(ReconLDowngrade, at_ns, u64, "int"),
        f!(ReconLDowngrade, detail, [u8; RECONL_MAX_MESSAGE], "ints"),
    ]);

    struct_layout(&mut c, "ReconLStatsDesc", size_of::<ReconLStatsDesc>(), &[
        f!(ReconLStatsDesc, base, StructHeader, "none"),
        f!(ReconLStatsDesc, include_downgrades, u32, "int"),
        f!(ReconLStatsDesc, reserved, u32, "int"),
    ]);

    struct_layout(&mut c, "ReconLFrameGenStats", size_of::<ReconLFrameGenStats>(), &[
        f!(ReconLFrameGenStats, ready, u32, "int"),
        f!(ReconLFrameGenStats, generated, u32, "int"),
        f!(ReconLFrameGenStats, generated_ns, u64, "int"),
        f!(ReconLFrameGenStats, last_ahead, f32, "float"),
        f!(ReconLFrameGenStats, reserved, u32, "int"),
        f!(ReconLFrameGenStats, reserved2, u32, "int"),
    ]);

    struct_layout(&mut c, "ReconLStats", size_of::<ReconLStats>(), &[
        f!(ReconLStats, base, StructHeader, "none"),
        f!(ReconLStats, backend, u32, "int"),
        f!(ReconLStats, tier, u32, "int"),
        f!(ReconLStats, tier_reason, u32, "int"),
        f!(ReconLStats, tier_locked, u32, "int"),
        f!(ReconLStats, frames_presented, u32, "int"),
        f!(ReconLStats, frames_dropped, u32, "int"),
        f!(ReconLStats, downgrade_count, u32, "int"),
        f!(ReconLStats, downgrade_capacity, u32, "int"),
        f!(ReconLStats, downgrades, [ReconLDowngrade; RECONL_MAX_DOWNGRADES], "none"),
        f!(ReconLStats, memory, ReconLMemoryStats, "none"),
        f!(ReconLStats, shadows, ReconLShadowStats, "none"),
        f!(ReconLStats, frame, ReconLFrameTiming, "none"),
        f!(ReconLStats, caps, u32, "int"),
        f!(ReconLStats, failures, u32, "int"),
        f!(ReconLStats, safe_path_events, u32, "int"),
        f!(ReconLStats, audit_divergences, u32, "int"),
        f!(ReconLStats, last_result, i32, "int"),
        f!(ReconLStats, tier_reason_text, [u8; RECONL_MAX_MESSAGE], "ints"),
        f!(ReconLStats, device_name, [u8; RECONL_MAX_NAME], "ints"),
        f!(ReconLStats, framegen, ReconLFrameGenStats, "none"),
    ]);

    struct_layout(&mut c, "ReconLErrorInfo", size_of::<ReconLErrorInfo>(), &[
        f!(ReconLErrorInfo, base, StructHeader, "none"),
        f!(ReconLErrorInfo, result, i32, "int"),
        f!(ReconLErrorInfo, message, [u8; RECONL_MAX_MESSAGE], "ints"),
        f!(ReconLErrorInfo, file, [u8; RECONL_MAX_PATH], "ints"),
        f!(ReconLErrorInfo, line, u32, "int"),
        f!(ReconLErrorInfo, function_name_index, u32, "int"),
        f!(ReconLErrorInfo, function, [u8; RECONL_MAX_NAME], "ints"),
    ]);

    struct_layout(&mut c, "ReconLCommandListDesc", size_of::<ReconLCommandListDesc>(), &[
        f!(ReconLCommandListDesc, base, StructHeader, "none"),
        f!(ReconLCommandListDesc, capacity_bytes, u32, "int"),
        f!(ReconLCommandListDesc, reserved, u32, "int"),
        f!(ReconLCommandListDesc, debug_name, *const i8, "ptr"),
    ]);

    struct_layout(&mut c, "ReconLColorAttachment", size_of::<ReconLColorAttachment>(), &[
        f!(ReconLColorAttachment, texture, *mut c_void, "ptr"),
        f!(ReconLColorAttachment, resolve, *mut c_void, "ptr"),
        f!(ReconLColorAttachment, mip, u32, "int"),
        f!(ReconLColorAttachment, layer, u32, "int"),
    ]);

    struct_layout(&mut c, "ReconLRenderPassDesc", size_of::<ReconLRenderPassDesc>(), &[
        f!(ReconLRenderPassDesc, base, StructHeader, "none"),
        f!(ReconLRenderPassDesc, color_count, u32, "int"),
        f!(ReconLRenderPassDesc, reserved, u32, "int"),
        f!(ReconLRenderPassDesc, color, [ReconLColorAttachment; RECONL_MAX_ATTACHMENTS], "none"),
        f!(ReconLRenderPassDesc, depth, *mut c_void, "ptr"),
        f!(ReconLRenderPassDesc, viewport_width, u32, "int"),
        f!(ReconLRenderPassDesc, viewport_height, u32, "int"),
        f!(ReconLRenderPassDesc, load_color, u32, "int"),
        f!(ReconLRenderPassDesc, load_depth, u32, "int"),
        f!(ReconLRenderPassDesc, clear_color, [f32; 4], "floats"),
        f!(ReconLRenderPassDesc, clear_depth, f32, "float"),
        f!(ReconLRenderPassDesc, stencil_clear, u32, "int"),
        f!(ReconLRenderPassDesc, reserved2, u32, "int"),
    ]);

    struct_layout(&mut c, "ReconLCamera", size_of::<ReconLCamera>(), &[
        f!(ReconLCamera, base, StructHeader, "none"),
        f!(ReconLCamera, view, [f32; 16], "floats"),
        f!(ReconLCamera, fov_y_deg, f32, "float"),
        f!(ReconLCamera, near, f32, "float"),
        f!(ReconLCamera, far, f32, "float"),
        f!(ReconLCamera, reserved, f32, "float"),
    ]);

    struct_layout(&mut c, "ReconLFrameGenDesc", size_of::<ReconLFrameGenDesc>(), &[
        f!(ReconLFrameGenDesc, base, StructHeader, "none"),
        f!(ReconLFrameGenDesc, enabled, u32, "int"),
        f!(ReconLFrameGenDesc, reserved, u32, "int"),
    ]);

    struct_layout(&mut c, "ReconLFrameDesc", size_of::<ReconLFrameDesc>(), &[
        f!(ReconLFrameDesc, base, StructHeader, "none"),
        f!(ReconLFrameDesc, width, u32, "int"),
        f!(ReconLFrameDesc, height, u32, "int"),
        f!(ReconLFrameDesc, seed, u32, "int"),
        f!(ReconLFrameDesc, reserved, u32, "int"),
        f!(ReconLFrameDesc, lights, *const ReconLLightList, "ptr"),
        f!(ReconLFrameDesc, shadows, *const ReconLShadowConfig, "ptr"),
        f!(ReconLFrameDesc, camera, *const ReconLCamera, "ptr"),
        f!(ReconLFrameDesc, framegen, *const ReconLFrameGenDesc, "ptr"),
    ]);

    struct_layout(&mut c, "ReconLPresentDesc", size_of::<ReconLPresentDesc>(), &[
        f!(ReconLPresentDesc, base, StructHeader, "none"),
        f!(ReconLPresentDesc, out_pixels, *mut c_void, "ptr"),
        f!(ReconLPresentDesc, out_pixels_size, u64, "int"),
        f!(ReconLPresentDesc, out_row_pitch, u32, "int"),
        f!(ReconLPresentDesc, out_format, u32, "int"),
        f!(ReconLPresentDesc, flip, u32, "int"),
    ]);

    constants(&mut c);
    c
}

/// A table row per constant: the header's spelling, the Rust value.
macro_rules! values {
    ($c:expr, $( $cname:literal = $rust:expr ),* $(,)?) => {
        $( value($c, $cname, $rust); )*
    };
}

/// One `_Static_assert` for a C macro or enumerator, against the Rust value the
/// implementation uses. The message is the constant's own name, so the compiler
/// says which value drifted.
fn value(c: &mut String, cname: &str, rust: i64) {
    let _ = writeln!(c, "_Static_assert({cname} == {rust}, \"{cname}: value\");");
}

/// The numeric contract: every macro and enumerator the header exports, each
/// asserted against the Rust value the implementation uses. `Code`, `Tier`,
/// `TierReason`, `ShadowFilter`, `ShadowEvent`, `Level`, `core::tier::caps` and
/// the raster pipeline enums are things the implementation branches on; the
/// mirror in `abi.rs` is the source for the groups it stores but does not read.
///
/// `RECONL_COMMAND_BYTES` is deliberately absent: its Rust owner is
/// `ffi/src/sizing.rs`, which compares it with the header line in its own unit
/// test, and that private constant is not reachable from a test crate.
fn constants(c: &mut String) {
    let _ = writeln!(c, "\n/* ---------------- capacities and version ---------------- */");
    values!(c,
        "RECONL_MAX_BACKENDS" = RECONL_MAX_BACKENDS as i64,
        "RECONL_MAX_DOWNGRADES" = RECONL_MAX_DOWNGRADES as i64,
        "RECONL_MAX_CASCADES" = RECONL_MAX_CASCADES as i64,
        "RECONL_MAX_LIGHTS" = RECONL_MAX_LIGHTS as i64,
        "RECONL_MAX_TEXTURE_SLOTS" = RECONL_MAX_TEXTURE_SLOTS as i64,
        "RECONL_MAX_ATTACHMENTS" = RECONL_MAX_ATTACHMENTS as i64,
        "RECONL_MAX_VERTEX_STREAMS" = RECONL_MAX_VERTEX_STREAMS as i64,
        "RECONL_MAX_CAPS" = RECONL_MAX_CAPS as i64,
        "RECONL_MAX_NAME" = RECONL_MAX_NAME as i64,
        "RECONL_MAX_MESSAGE" = RECONL_MAX_MESSAGE as i64,
        "RECONL_MAX_PATH" = RECONL_MAX_PATH as i64,
        "RECONL_TIER_COUNT" = RECONL_TIER_COUNT as i64,
        "RECONL_VERSION_MAJOR" = VERSION_MAJOR as i64,
        "RECONL_VERSION_MINOR" = VERSION_MINOR as i64,
        "RECONL_VERSION_PATCH" = VERSION_PATCH as i64,
        "RECONL_ABI_VERSION" = ABI_VERSION as i64,
    );

    let _ = writeln!(c, "\n/* ---------------- result codes ---------------- */");
    // Every entry point returns `Code`; `abi::result` is the second mirror. Both
    // must equal the header's numbers, which is also what keeps the two equal to
    // each other.
    values!(c,
        "RECONL_OK" = Code::Ok as i32 as i64,
        "RECONL_ERR_INVALID_ARGUMENT" = Code::InvalidArgument as i32 as i64,
        "RECONL_ERR_OUT_OF_MEMORY" = Code::OutOfMemory as i32 as i64,
        "RECONL_ERR_NOT_SUPPORTED" = Code::NotSupported as i32 as i64,
        "RECONL_ERR_BACKEND_UNAVAILABLE" = Code::BackendUnavailable as i32 as i64,
        "RECONL_ERR_BUDGET_EXCEEDED" = Code::BudgetExceeded as i32 as i64,
        "RECONL_ERR_DEVICE_LOST" = Code::DeviceLost as i32 as i64,
        "RECONL_ERR_INVALID_HANDLE" = Code::InvalidHandle as i32 as i64,
        "RECONL_ERR_STRUCT_SIZE" = Code::StructSize as i32 as i64,
        "RECONL_ERR_WRONG_STRUCT_TYPE" = Code::WrongStructType as i32 as i64,
        "RECONL_ERR_ABI_VERSION" = Code::AbiVersion as i32 as i64,
        "RECONL_ERR_FRAME_IN_PROGRESS" = Code::FrameInProgress as i32 as i64,
        "RECONL_ERR_NO_FRAME" = Code::NoFrame as i32 as i64,
        "RECONL_ERR_NOT_READY" = Code::NotReady as i32 as i64,
        "RECONL_ERR_IO" = Code::Io as i32 as i64,
        "RECONL_ERR_CORRUPT_CACHE" = Code::CorruptCache as i32 as i64,
        "RECONL_ERR_DEGRADED" = Code::Degraded as i32 as i64,
        "RECONL_ERR_PANIC" = Code::Panic as i32 as i64,
        "RECONL_ERR_EMPTY_FRAME" = Code::EmptyFrame as i32 as i64,
    );
    values!(c,
        "RECONL_OK" = result::OK as i64,
        "RECONL_ERR_INVALID_ARGUMENT" = result::INVALID_ARGUMENT as i64,
        "RECONL_ERR_OUT_OF_MEMORY" = result::OUT_OF_MEMORY as i64,
        "RECONL_ERR_NOT_SUPPORTED" = result::NOT_SUPPORTED as i64,
        "RECONL_ERR_BACKEND_UNAVAILABLE" = result::BACKEND_UNAVAILABLE as i64,
        "RECONL_ERR_BUDGET_EXCEEDED" = result::BUDGET_EXCEEDED as i64,
        "RECONL_ERR_DEVICE_LOST" = result::DEVICE_LOST as i64,
        "RECONL_ERR_INVALID_HANDLE" = result::INVALID_HANDLE as i64,
        "RECONL_ERR_STRUCT_SIZE" = result::STRUCT_SIZE as i64,
        "RECONL_ERR_WRONG_STRUCT_TYPE" = result::WRONG_STRUCT_TYPE as i64,
        "RECONL_ERR_ABI_VERSION" = result::ABI_VERSION as i64,
        "RECONL_ERR_FRAME_IN_PROGRESS" = result::FRAME_IN_PROGRESS as i64,
        "RECONL_ERR_NO_FRAME" = result::NO_FRAME as i64,
        "RECONL_ERR_NOT_READY" = result::NOT_READY as i64,
        "RECONL_ERR_IO" = result::IO as i64,
        "RECONL_ERR_CORRUPT_CACHE" = result::CORRUPT_CACHE as i64,
        "RECONL_ERR_DEGRADED" = result::DEGRADED as i64,
        "RECONL_ERR_PANIC" = result::PANIC as i64,
        "RECONL_ERR_EMPTY_FRAME" = result::EMPTY_FRAME as i64,
    );

    let _ = writeln!(c, "\n/* ---------------- struct types ---------------- */");
    values!(c,
        "RECONL_STRUCT_NONE" = struct_type::NONE as i64,
        "RECONL_STRUCT_ALLOCATOR" = struct_type::ALLOCATOR as i64,
        "RECONL_STRUCT_PROBE_DESC" = struct_type::PROBE_DESC as i64,
        "RECONL_STRUCT_PROBE_INFO" = struct_type::PROBE_INFO as i64,
        "RECONL_STRUCT_MEMORY_BUDGET" = struct_type::MEMORY_BUDGET as i64,
        "RECONL_STRUCT_DEVICE_LIMITS" = struct_type::DEVICE_LIMITS as i64,
        "RECONL_STRUCT_DEVICE_DESC" = struct_type::DEVICE_DESC as i64,
        "RECONL_STRUCT_BUFFER_DESC" = struct_type::BUFFER_DESC as i64,
        "RECONL_STRUCT_TEXTURE_DESC" = struct_type::TEXTURE_DESC as i64,
        "RECONL_STRUCT_SAMPLER_DESC" = struct_type::SAMPLER_DESC as i64,
        "RECONL_STRUCT_PIPELINE_DESC" = struct_type::PIPELINE_DESC as i64,
        "RECONL_STRUCT_COMMAND_LIST_DESC" = struct_type::COMMAND_LIST_DESC as i64,
        "RECONL_STRUCT_RENDER_PASS_DESC" = struct_type::RENDER_PASS_DESC as i64,
        "RECONL_STRUCT_SWAPCHAIN_DESC" = struct_type::SWAPCHAIN_DESC as i64,
        "RECONL_STRUCT_FRAME_DESC" = struct_type::FRAME_DESC as i64,
        "RECONL_STRUCT_PRESENT_DESC" = struct_type::PRESENT_DESC as i64,
        "RECONL_STRUCT_SHADOW_CONFIG" = struct_type::SHADOW_CONFIG as i64,
        "RECONL_STRUCT_STATS" = struct_type::STATS as i64,
        "RECONL_STRUCT_LIGHT" = struct_type::LIGHT as i64,
        "RECONL_STRUCT_LIGHT_LIST" = struct_type::LIGHT_LIST as i64,
        "RECONL_STRUCT_ERROR_INFO" = struct_type::ERROR_INFO as i64,
        "RECONL_STRUCT_CAMERA" = struct_type::CAMERA as i64,
        "RECONL_STRUCT_FRAME_GEN" = struct_type::FRAME_GEN as i64,
        "RECONL_STRUCT_SOFTCPU_DESC" = struct_type::SOFTCPU_DESC as i64,
        "RECONL_STRUCT_NULL_DESC" = struct_type::NULL_DESC as i64,
        "RECONL_STRUCT_D3D11_DESC" = struct_type::D3D11_DESC as i64,
    );

    let _ = writeln!(c, "\n/* ---------------- backends, tiers and reasons ---------------- */");
    values!(c,
        "RECONL_BACKEND_NONE" = backend::NONE as i64,
        "RECONL_BACKEND_SOFT_CPU" = backend::SOFT_CPU as i64,
        "RECONL_BACKEND_NULL" = backend::NULL as i64,
        "RECONL_BACKEND_D3D11" = backend::D3D11 as i64,
        "RECONL_BACKEND_D3D12" = backend::D3D12 as i64,
        "RECONL_BACKEND_VULKAN" = backend::VULKAN as i64,
        "RECONL_BACKEND_GL" = backend::GL as i64,
        "RECONL_BACKEND_METAL" = backend::METAL as i64,
        "RECONL_BACKEND_WEBGPU" = backend::WEBGPU as i64,
        "RECONL_BACKEND_WASM_WEBGL2" = backend::WASM_WEBGL2 as i64,
        "RECONL_TIER_T0_GPU_DISCRETE" = Tier::GpuDiscrete as u32 as i64,
        "RECONL_TIER_T1_GPU_SHARED" = Tier::GpuShared as u32 as i64,
        "RECONL_TIER_T2_CPU_RAM" = Tier::CpuRam as u32 as i64,
        "RECONL_TIER_T3_CPU_THRIFTY" = Tier::CpuThrifty as u32 as i64,
        "RECONL_TIER_T4_OUT_OF_CORE" = Tier::OutOfCore as u32 as i64,
        "RECONL_TIER_REASON_STARTUP_PROBE" = TierReason::StartupProbe as i32 as i64,
        "RECONL_TIER_REASON_HOST_REQUEST" = TierReason::HostRequest as i32 as i64,
        "RECONL_TIER_REASON_ALLOCATION_OVER_BUDGET" = TierReason::AllocationOverBudget as i32 as i64,
        "RECONL_TIER_REASON_FRAME_TIME_OVER_TARGET" = TierReason::FrameTimeOverTarget as i32 as i64,
        "RECONL_TIER_REASON_DEVICE_REMOVED" = TierReason::DeviceRemoved as i32 as i64,
        "RECONL_TIER_REASON_DEVICE_LOST" = TierReason::DeviceLost as i32 as i64,
        "RECONL_TIER_REASON_MEMORY_PRESSURE" = TierReason::MemoryPressure as i32 as i64,
        "RECONL_TIER_REASON_DISK_CACHE_FULL" = TierReason::DiskCacheFull as i32 as i64,
        "RECONL_TIER_REASON_BUILD" = TierReason::Build as i32 as i64,
        "RECONL_TIER_REASON_NO_GPU_API" = TierReason::NoGpuApi as i32 as i64,
        "RECONL_TIER_REASON_RECOVERY" = TierReason::Recovery as i32 as i64,
    );

    let _ = writeln!(c, "\n/* ---------------- caps and downgrade flags ---------------- */");
    // Two Rust copies exist: `abi::caps` (the mirror) and `core::tier::caps`
    // (what the backends set). The header has to equal both.
    values!(c,
        "RECONL_CAP_NONE" = 0,
        "RECONL_CAP_TEXTURES" = caps::TEXTURES as i64,
        "RECONL_CAP_MIPMAPS" = caps::MIPMAPS as i64,
        "RECONL_CAP_SHADOWS" = caps::SHADOWS as i64,
        "RECONL_CAP_PCF_5X5" = caps::PCF_5X5 as i64,
        "RECONL_CAP_PCSS_LITE" = caps::PCSS_LITE as i64,
        "RECONL_CAP_DISK_SPILL" = caps::DISK_SPILL as i64,
        "RECONL_CAP_MULTITHREAD" = caps::MULTITHREAD as i64,
        "RECONL_CAP_OUT_OF_CORE" = caps::OUT_OF_CORE as i64,
        "RECONL_CAP_CACHED_CASCADE" = caps::CACHED_CASCADE as i64,
        "RECONL_CAP_SIMD_SSE2" = caps::SIMD_SSE2 as i64,
        "RECONL_CAP_SIMD_AVX2" = caps::SIMD_AVX2 as i64,
        "RECONL_CAP_SIMD_NEON" = caps::SIMD_NEON as i64,
        "RECONL_CAP_SIMD_WASM128" = caps::SIMD_WASM128 as i64,
        "RECONL_CAP_COMPUTE" = caps::COMPUTE as i64,
        "RECONL_CAP_PRESENT_TO_MEMORY" = caps::PRESENT_TO_MEMORY as i64,
    );
    values!(c,
        "RECONL_CAP_TEXTURES" = core_tier::caps::TEXTURES as i64,
        "RECONL_CAP_MIPMAPS" = core_tier::caps::MIPMAPS as i64,
        "RECONL_CAP_SHADOWS" = core_tier::caps::SHADOWS as i64,
        "RECONL_CAP_PCF_5X5" = core_tier::caps::PCF_5X5 as i64,
        "RECONL_CAP_PCSS_LITE" = core_tier::caps::PCSS_LITE as i64,
        "RECONL_CAP_DISK_SPILL" = core_tier::caps::DISK_SPILL as i64,
        "RECONL_CAP_MULTITHREAD" = core_tier::caps::MULTITHREAD as i64,
        "RECONL_CAP_OUT_OF_CORE" = core_tier::caps::OUT_OF_CORE as i64,
        "RECONL_CAP_CACHED_CASCADE" = core_tier::caps::CACHED_CASCADE as i64,
        "RECONL_CAP_SIMD_SSE2" = core_tier::caps::SIMD_SSE2 as i64,
        "RECONL_CAP_SIMD_AVX2" = core_tier::caps::SIMD_AVX2 as i64,
        "RECONL_CAP_SIMD_NEON" = core_tier::caps::SIMD_NEON as i64,
        "RECONL_CAP_SIMD_WASM128" = core_tier::caps::SIMD_WASM128 as i64,
        "RECONL_CAP_COMPUTE" = core_tier::caps::COMPUTE as i64,
        "RECONL_CAP_PRESENT_TO_MEMORY" = core_tier::caps::PRESENT_TO_MEMORY as i64,
    );
    values!(c,
        "RECONL_ALLOW_DOWNGRADE_NONE" = allow_downgrade::NONE as i64,
        "RECONL_ALLOW_DOWNGRADE_TIER" = allow_downgrade::TIER as i64,
        "RECONL_ALLOW_DOWNGRADE_SHADOWS" = allow_downgrade::SHADOWS as i64,
        "RECONL_ALLOW_DOWNGRADE_RESOLUTION" = allow_downgrade::RESOLUTION as i64,
        "RECONL_ALLOW_DOWNGRADE_DISK" = allow_downgrade::DISK as i64,
        "RECONL_ALLOW_DOWNGRADE_FREEZE_CACHE" = allow_downgrade::FREEZE_CACHE as i64,
        "RECONL_ALLOW_DOWNGRADE_ALL" = allow_downgrade::ALL as i64,
    );

    let _ = writeln!(c, "\n/* ---------------- log, formats, usages, index ---------------- */");
    values!(c,
        "RECONL_LOG_OFF" = Level::Off as u32 as i64,
        "RECONL_LOG_ERROR" = Level::Error as u32 as i64,
        "RECONL_LOG_WARN" = Level::Warn as u32 as i64,
        "RECONL_LOG_INFO" = Level::Info as u32 as i64,
        "RECONL_LOG_DEBUG" = Level::Debug as u32 as i64,
        "RECONL_LOG_TRACE" = Level::Trace as u32 as i64,
        "RECONL_FORMAT_UNKNOWN" = format::UNKNOWN as i64,
        "RECONL_FORMAT_R8G8B8A8_UNORM" = format::R8G8B8A8_UNORM as i64,
        "RECONL_FORMAT_B8G8R8A8_UNORM" = format::B8G8R8A8_UNORM as i64,
        "RECONL_FORMAT_R8G8B8A8_SRGB" = format::R8G8B8A8_SRGB as i64,
        "RECONL_FORMAT_R32_FLOAT" = format::R32_FLOAT as i64,
        "RECONL_FORMAT_R32G32_FLOAT" = format::R32G32_FLOAT as i64,
        "RECONL_FORMAT_R32G32B32_FLOAT" = format::R32G32B32_FLOAT as i64,
        "RECONL_FORMAT_R32G32B32A32_FLOAT" = format::R32G32B32A32_FLOAT as i64,
        "RECONL_FORMAT_D32_FLOAT" = format::D32_FLOAT as i64,
        "RECONL_BUFFER_VERTEX" = buffer_usage::VERTEX as i64,
        "RECONL_BUFFER_INDEX" = buffer_usage::INDEX as i64,
        "RECONL_BUFFER_UNIFORM" = buffer_usage::UNIFORM as i64,
        "RECONL_BUFFER_UPLOAD" = buffer_usage::UPLOAD as i64,
        "RECONL_BUFFER_READBACK" = buffer_usage::READBACK as i64,
        "RECONL_BUFFER_STATIC" = buffer_usage::STATIC as i64,
        "RECONL_BUFFER_DYNAMIC" = buffer_usage::DYNAMIC as i64,
        "RECONL_TEXTURE_SAMPLED" = texture_usage::SAMPLED as i64,
        "RECONL_TEXTURE_RENDER_TARGET" = texture_usage::RENDER_TARGET as i64,
        "RECONL_TEXTURE_DEPTH_STENCIL" = texture_usage::DEPTH_STENCIL as i64,
        "RECONL_TEXTURE_SHADOW_MAP" = texture_usage::SHADOW_MAP as i64,
        "RECONL_TEXTURE_HOST_READBACK" = texture_usage::HOST_READBACK as i64,
        "RECONL_TEXTURE_MIPMAPPED" = texture_usage::MIPMAPPED as i64,
        "RECONL_TEXTURE_STATIC" = texture_usage::STATIC as i64,
        "RECONL_INDEX_UINT16" = index_format::UINT16 as i64,
        "RECONL_INDEX_UINT32" = index_format::UINT32 as i64,
    );

    let _ = writeln!(c, "\n/* ---------------- pipeline, texture and light enums ---------------- */");
    values!(c,
        "RECONL_SHADING_UNLIT" = shading::UNLIT as i64,
        "RECONL_SHADING_LAMBERT" = shading::LAMBERT as i64,
        "RECONL_SHADING_TEXTURED" = shading::TEXTURED as i64,
        "RECONL_SHADING_TEXTURED_LAMBERT" = shading::TEXTURED_LAMBERT as i64,
        "RECONL_BLEND_OPAQUE" = shade::BLEND_OPAQUE as i64,
        "RECONL_BLEND_ALPHA" = shade::BLEND_ALPHA as i64,
        "RECONL_BLEND_ADDITIVE" = shade::BLEND_ADDITIVE as i64,
        "RECONL_BLEND_MULTIPLY" = shade::BLEND_MULTIPLY as i64,
        "RECONL_COMPARE_LESS" = COMPARE_LESS as i64,
        "RECONL_COMPARE_GREATER" = COMPARE_GREATER as i64,
        "RECONL_CULL_NONE" = CULL_NONE as i64,
        "RECONL_CULL_BACK" = CULL_BACK as i64,
        "RECONL_CULL_FRONT" = CULL_FRONT as i64,
        "RECONL_FILTER_NEAREST" = texture::FILTER_NEAREST as i64,
        "RECONL_FILTER_LINEAR" = texture::FILTER_LINEAR as i64,
        "RECONL_FILTER_NEAREST_MIP_LINEAR" = texture::FILTER_NEAREST_MIP_LINEAR as i64,
        "RECONL_FILTER_LINEAR_MIP_LINEAR" = texture::FILTER_LINEAR_MIP_LINEAR as i64,
        "RECONL_WRAP_REPEAT" = texture::WRAP_REPEAT as i64,
        "RECONL_WRAP_CLAMP" = texture::WRAP_CLAMP as i64,
        "RECONL_WRAP_MIRROR" = texture::WRAP_MIRROR as i64,
        "RECONL_LIGHT_DIRECTIONAL" = shade::LIGHT_DIRECTIONAL as i64,
        "RECONL_LIGHT_SPOT" = shade::LIGHT_SPOT as i64,
        "RECONL_LIGHT_POINT" = shade::LIGHT_POINT as i64,
    );

    let _ = writeln!(c, "\n/* ---------------- shadows and frame state ---------------- */");
    values!(c,
        "RECONL_SHADOW_FILTER_HARD" = ShadowFilter::Hard as u32 as i64,
        "RECONL_SHADOW_FILTER_PCF3X3" = ShadowFilter::Pcf3x3 as u32 as i64,
        "RECONL_SHADOW_FILTER_PCF5X5" = ShadowFilter::Pcf5x5 as u32 as i64,
        "RECONL_SHADOW_FILTER_PCSS_LITE" = ShadowFilter::PcssLite as u32 as i64,
    );
    values!(c,
        "RECONL_SHADOW_FILTER_HARD" = shade::FILTER_HARD as i64,
        "RECONL_SHADOW_FILTER_PCF3X3" = shade::FILTER_PCF3X3 as i64,
        "RECONL_SHADOW_FILTER_PCF5X5" = shade::FILTER_PCF5X5 as i64,
        "RECONL_SHADOW_FILTER_PCSS_LITE" = shade::FILTER_PCSS_LITE as i64,
    );
    values!(c,
        "RECONL_SHADOW_EVENT_NONE" = ShadowEvent::None as u32 as i64,
        "RECONL_SHADOW_EVENT_CASCADE_DROPPED" = ShadowEvent::CascadeDropped as u32 as i64,
        "RECONL_SHADOW_EVENT_MAP_BUDGET_CLAMPED" = ShadowEvent::MapBudgetClamped as u32 as i64,
        "RECONL_SHADOW_EVENT_CACHE_HIT" = ShadowEvent::CacheHit as u32 as i64,
        "RECONL_SHADOW_EVENT_CACHE_MISS" = ShadowEvent::CacheMiss as u32 as i64,
        "RECONL_SHADOW_EVENT_CACHE_CORRUPT" = ShadowEvent::CacheCorrupt as u32 as i64,
        "RECONL_SHADOW_EVENT_FALLBACK_UNSHADOWED" = ShadowEvent::FallbackUnshadowed as u32 as i64,
        "RECONL_SHADOW_EVENT_FILTER_DOWNGRADED" = ShadowEvent::FilterDowngraded as u32 as i64,
        "RECONL_SHADOW_EVENT_FROZEN_CASCADE" = ShadowEvent::FrozenCascade as u32 as i64,
        "RECONL_FRAME_IDLE" = frame_state::IDLE as i64,
        "RECONL_FRAME_OPEN" = frame_state::OPEN as i64,
        "RECONL_FRAME_SUBMITTED" = frame_state::SUBMITTED as i64,
        "RECONL_FRAME_PRESENTED" = frame_state::PRESENTED as i64,
    );
}

/// One struct's asserts: its total size, then for every field its offset, its
/// size and its category.
fn struct_layout(c: &mut String, cname: &str, rust_size: usize, fields: &[(&str, usize, usize, &str)]) {
    let _ = writeln!(c, "\n/* {cname}: {rust_size} bytes in Rust */");
    let _ = writeln!(c, "_Static_assert(sizeof({cname}) == {rust_size}, \"{cname}: sizeof\");");
    for &(field, offset, size, kind) in fields {
        let expr = format!("(({cname}*)0)->{field}");
        let _ = writeln!(c, "_Static_assert(offsetof({cname}, {field}) == {offset}, \"{cname}::{field}: offset\");");
        let _ = writeln!(c, "_Static_assert(sizeof({expr}) == {size}, \"{cname}::{field}: size\");");
        category_assert(c, cname, field, &expr, kind);
    }
}

const INTEGERS: &str = "char: 1, signed char: 1, unsigned char: 1, short: 1, unsigned short: 1, \
                        int: 1, unsigned int: 1, long: 1, unsigned long: 1, long long: 1, \
                        unsigned long long: 1, _Bool: 1";
const FLOATS: &str = "float: 1, double: 1, long double: 1";

/// The category a field's Rust type declares, checked against what the header's
/// C type selects. Width is already pinned by the `sizeof` assert; this catches
/// a same-width retype, e.g. `u32` becoming `f32` or a pointer.
fn category_assert(c: &mut String, cname: &str, field: &str, expr: &str, kind: &str) {
    let _ = match kind {
        "int" => writeln!(
            c,
            "_Static_assert(_Generic({expr}, {INTEGERS}, default: 0), \"{cname}::{field}: an integer field\");"
        ),
        "float" => writeln!(
            c,
            "_Static_assert(_Generic({expr}, {FLOATS}, default: 0), \"{cname}::{field}: a float field\");"
        ),
        "ints" => writeln!(
            c,
            "_Static_assert(_Generic({expr}[0], {INTEGERS}, default: 0), \"{cname}::{field}: an integer array\");"
        ),
        "floats" => writeln!(
            c,
            "_Static_assert(_Generic({expr}[0], {FLOATS}, default: 0), \"{cname}::{field}: a float array\");"
        ),
        "ptr" => writeln!(
            c,
            "_Static_assert(!_Generic({expr}, {INTEGERS}, {FLOATS}, default: 0), \
             \"{cname}::{field}: a pointer, not a number\");\n\
             _Static_assert(sizeof({expr}) == sizeof(void *), \"{cname}::{field}: pointer width\");"
        ),
        "none" => Ok(()),
        other => panic!("abi_layout: {cname}::{field} has unknown kind {other:?}"),
    };
}
